[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "terrain_pkg"
version = "0.1.0"
description = "Terrain Scraper"
requires-python = ">=3.9"

[tool.setuptools.packages.find]
where = ["src"]